# Generated by Django 2.2.3 on 2019-07-01 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dancarino',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('perfil', models.CharField(max_length=50, verbose_name='perfil')),
                ('curso', models.CharField(max_length=30, verbose_name='cursos')),
                ('idade', models.DateField(verbose_name='idade')),
                ('imagem', models.ImageField(upload_to='templates')),
            ],
        ),
        migrations.CreateModel(
            name='Estilos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
            ],
        ),
    ]
