# Generated by Django 2.2.2 on 2019-07-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dancarinos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('biografia', models.CharField(max_length=1000, null=True, verbose_name='Biografia')),
                ('curso', models.CharField(max_length=30, verbose_name='Curso')),
                ('idade', models.IntegerField(verbose_name='Idade')),
                ('foto', models.ImageField(null=True, upload_to='templates', verbose_name='Foto')),
                ('estilo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Estilos')),
            ],
        ),
        migrations.DeleteModel(
            name='Dancarino',
        ),
    ]
